/* CavaPasMarcher — API bridge for briefs, artifacts and server versions. */
(function () {
  const API = window.CPM_API_URL || 'http://localhost:8787/api'; const $ = (id) => document.getElementById(id); const value = (id) => $(id)?.value?.trim() || '';
  const toast = (message) => { const el = $('toast'); if (!el) return; el.textContent = message; el.classList.add('show'); window.setTimeout(() => el.classList.remove('show'), 2800); };
  const languages = () => [...document.querySelectorAll('#language-checks input:checked')].map((input) => input.value);
  const local = () => { try { return JSON.parse(localStorage.getItem('cpm-last-project') || 'null'); } catch { return null; } };
  const brief = () => ({ name:value('gen-name'), sector:value('gen-sector'), country:value('gen-country') || 'FR', city:value('gen-city'), plan:value('gen-plan') || 'pro', language:value('gen-language') || 'fr', languages:languages(), description:value('gen-description') });
  async function request(path, options) { const response = await fetch(`${API}${path}`, options); if (!response.ok) throw new Error(`API ${response.status}`); return response; }
  async function saveCurrentProject() { const project = brief(); if (!project.name || !project.sector) return; const existing = local(); const method = existing?.id ? 'PUT' : 'POST'; const path = existing?.id ? `/projects/${encodeURIComponent(existing.id)}` : '/projects'; try { const saved = await (await request(path, { method, headers:{'content-type':'application/json'}, body:JSON.stringify(project) })).json(); localStorage.setItem('cpm-last-project', JSON.stringify(saved)); const generated = window.CPMGeneratedSite; if (generated?.html && saved.id) { await request(`/projects/${encodeURIComponent(saved.id)}/site`, { method:'PUT', headers:{'content-type':'application/json'}, body:JSON.stringify({ html:generated.html }) }); await request(`/projects/${encodeURIComponent(saved.id)}/versions`, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ html:generated.html, name:project.name, project:{...project, pricing:saved.pricing} }) }); } toast('Site, brief et version serveur enregistrés.'); } catch { localStorage.setItem('cpm-last-project', JSON.stringify({...project, site:window.CPMGeneratedSite?.html ? {html:window.CPMGeneratedSite.html} : undefined, localOnly:true})); toast('Site généré — sauvegarde locale active.'); } }
  document.addEventListener('click', (event) => { if (event.target.closest('#generate-site')) window.setTimeout(saveCurrentProject, 250); });
  window.CPMProjects = { async all(){ return (await request('/projects')).json().then((data) => data.projects || []); }, async get(id){ return (await request(`/projects/${encodeURIComponent(id)}`)).json(); }, async remove(id){ await request(`/projects/${encodeURIComponent(id)}`, {method:'DELETE'}); }, async update(id, project){ return (await request(`/projects/${encodeURIComponent(id)}`, {method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(project)})).json(); }, async saveSite(id, html){ return (await request(`/projects/${encodeURIComponent(id)}/site`, {method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({html})})).json(); }, async versions(id){ return (await request(`/projects/${encodeURIComponent(id)}/versions`)).json().then((data) => data.versions || []); }, async saveVersion(id, payload){ return (await request(`/projects/${encodeURIComponent(id)}/versions`, {method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})).json(); } };
})();
