const prospects=[
 {name:'Atelier Morel',type:'Architecte · Lyon',icon:'⌂',score:94,status:'À contacter',issue:'Aucun site détecté',color:'orange'},
 {name:'Maison Solaire',type:'Chauffagiste · Nantes',icon:'☼',score:88,status:'À contacter',issue:'Site non responsive',color:'yellow'},
 {name:'Le Bistrot Marin',type:'Restaurant · Bordeaux',icon:'♨',score:81,status:'Devis envoyé',issue:'Référencement faible',color:'blue'},
 {name:'Clinique Vétérinaire Atlas',type:'Santé · Paris',icon:'✚',score:76,status:'À qualifier',issue:'Site datant de 2015',color:'green'},
 {name:'Garage du Centre',type:'Automobile · Lille',icon:'⚙',score:71,status:'À qualifier',issue:'Pas de prise de RDV',color:'grey'}
];
const state={page:'overview',selected:null};
const app=document.getElementById('app');
function layout(content){return `<div class="page">${content}</div>`}
function header(eyebrow,title,sub,button=''){return `<div class="headline"><div><div class="eyebrow">${eyebrow}</div><h1 class="page-title">${title}</h1><p class="page-subtitle">${sub}</p></div>${button?`<button class="primary-btn" data-action="${button.action}">${button.label}</button>`:''}</div>`}
function overview(){return layout(header('JEUDI 18 SEPTEMBRE 2026','Bonjour Walid <span style="color:#b6c2ba">✦</span>','Voici ce qui se passe dans votre agence aujourd’hui.',{label:'+ Nouveau prospect',action:'new-prospect'})+`<div class="cards"><div class="card metric"><span class="metric-label">Prospects détectés</span><div class="metric-value">248</div><span class="metric-change">↑ 18,4% ce mois-ci</span></div><div class="card metric"><span class="metric-label">Score moyen</span><div class="metric-value">76<span style="font-size:14px;color:#9aa69d">/100</span></div><span class="metric-change">↑ 4,2 pts ce mois-ci</span></div><div class="card metric"><span class="metric-label">Devis en attente</span><div class="metric-value">8</div><span class="metric-change down">↓ 2 depuis hier</span></div><div class="card metric"><span class="metric-label">MRR prévisionnel</span><div class="metric-value">4 920 €</div><span class="metric-change">↑ 12,6% ce mois-ci</span></div></div><div class="grid-2"><section class="panel"><div class="panel-head"><h2 class="panel-title">Activité commerciale</h2><select class="field input" style="border:0;color:#718077"><option>6 derniers mois</option></select></div><div class="bars">${[48,65,58,85,72,100].map((x,i)=>`<div class="bar-wrap"><div class="bar ${i===5?'highlight':''}" style="height:${x}%"></div><span class="bar-label">${['Avr','Mai','Juin','Juil','Août','Sep'][i]}</span></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2 class="panel-title">À traiter en priorité</h2><span class="link" data-page="prospects">Voir tout →</span></div><div class="priority-list">${prospects.slice(0,4).map(p=>`<div class="priority"><div class="priority-icon">${p.icon}</div><div class="priority-info"><strong>${p.name}</strong><small>${p.issue}</small></div><span class="score">${p.score}</span></div>`).join('')}</div></section></div><section class="panel table-panel"><div class="panel-head"><h2 class="panel-title">Derniers prospects</h2><span class="link" data-page="prospects">Tous les prospects →</span></div>${prospectTable(prospects.slice(0,4))}</section>`)}
function prospectTable(items){return `<div class="table-wrap"><table><thead><tr><th>ENTREPRISE</th><th>SECTEUR</th><th>OPPORTUNITÉ</th><th>STATUT</th><th></th></tr></thead><tbody>${items.map((p,i)=>`<tr><td><div class="business"><span class="biz-icon">${p.icon}</span>${p.name}</div></td><td>${p.type}</td><td><span class="score-pill">${p.score}/100</span></td><td><span class="tag ${p.status==='Devis envoyé'?'green':''}">${p.status}</span></td><td><button class="secondary-btn" style="padding:6px 10px;font-size:11px" data-prospect="${i}">Voir</button></td></tr>`).join('')}</tbody></table></div>`}
function prospectsPage(){return layout(header('PROSPECTION','Vos prospects','Les entreprises qui ont le plus besoin de vous, classées par opportunité.',{label:'⌁ Scanner un territoire',action:'scan'})+`<section class="panel table-panel" style="margin-top:0"><div class="panel-head"><h2 class="panel-title">248 entreprises détectées</h2><div><select class="secondary-btn"><option>Score décroissant</option><option>Plus récent</option></select></div></div>${prospectTable(prospects)}</section>`)}
function quotesPage(){return layout(header('VENTES','Devis & offres','Transformez une opportunité en client récurrent.',{label:'+ Créer un devis',action:'new-quote'})+`<div class="quote-grid"><article class="panel package"><h3>Essentiel</h3><small>Pour démarrer proprement</small><div class="price">2 900 €</div><small>puis 149 €/mois</small><ul><li>Site 5 pages sur mesure</li><li>Version mobile</li><li>SEO local de base</li><li>Maintenance technique</li></ul><button class="secondary-btn" data-action="new-quote">Créer un devis</button></article><article class="panel package featured"><span class="badge">POPULAIRE</span><h3>Signature</h3><small>Pour accélérer la croissance</small><div class="price">6 900 €</div><small>puis 290 €/mois</small><ul><li>Site 10 pages sur mesure</li><li>Direction artistique dédiée</li><li>SEO local avancé</li><li>Ajout de contenu mensuel</li></ul><button class="primary-btn" data-action="new-quote">Créer un devis</button></article><article class="panel package"><h3>Premium</h3><small>Pour devenir une référence</small><div class="price">18 900 €</div><small>puis 690 €/mois</small><ul><li>Site illimité et multilingue</li><li>Identité visuelle complète</li><li>Stratégie SEO continue</li><li>Support prioritaire</li></ul><button class="secondary-btn" data-action="new-quote">Créer un devis</button></article></div><section class="panel table-panel"><div class="panel-head"><h2 class="panel-title">Devis récents</h2></div>${prospectTable(prospects.slice(2))}</section>`)}
function sitesPage(){return layout(header('PRODUCTION','Sites en cours','Suivez les créations et livraisons de vos clients.',{label:'+ Nouveau site',action:'new-site'})+`<div class="site-grid"><article class="panel site-card"><div class="site-thumb"><small>ATELIER MOREL</small><br/><strong>L’espace<br/>qui vous ressemble.</strong></div><div class="site-body"><strong>Atelier Morel</strong><small>Direction artistique · En production</small><br/><span class="tag">65% terminé</span></div></article><article class="panel site-card"><div class="site-thumb orange"><small>LE BISTROT MARIN</small><br/><strong>La mer<br/>à votre table.</strong></div><div class="site-body"><strong>Le Bistrot Marin</strong><small>Site vitrine · En validation</small><br/><span class="tag green">Prêt à livrer</span></div></article><article class="panel site-card"><div class="site-thumb blue"><small>CLINIQUE ATLAS</small><br/><strong>Bien soigner,<br/>simplement.</strong></div><div class="site-body"><strong>Clinique Atlas</strong><small>Site premium · Brief reçu</small><br/><span class="tag">10% terminé</span></div></article></div>`)}
function libraryPage(){return layout(header('BIBLIOTHÈQUE','Univers visuels','Des directions artistiques pensées pour chaque métier.',{label:'+ Créer un univers',action:'new-universe'})+`<div class="site-grid">${['Maison & habitat','Table & terroir','Santé & sérénité','Services experts','Mobilité & atelier','Bien-être & beauté'].map((x,i)=>`<article class="panel site-card"><div class="site-thumb ${['','orange','blue'][i%3]}"><small>UNIVERS 0${i+1}</small><br/><strong>${x}</strong></div><div class="site-body"><strong>${i%2?'3':'2'} formules disponibles</strong><small>Dernière mise à jour il y a ${i+1} j</small></div></article>`).join('')}</div>`)}
function settingsPage(){return layout(header('ESPACE','Réglages','Configurez votre agence et vos préférences.',{label:'Enregistrer',action:'save'})+`<section class="panel"><div class="form-grid"><div class="field"><label>Nom de l’agence</label><input value="CavaPasMarcher" /></div><div class="field"><label>Email de contact</label><input value="walid@example.com" /></div><div class="field"><label>Pays principal</label><select><option>France — EUR</option><option>Maroc — MAD</option><option>Belgique — EUR</option></select></div><div class="field"><label>Langue de l’interface</label><select><option>Français</option><option>English</option></select></div><div class="field full"><label>Signature commerciale</label><textarea>Des sites qui ne ressemblent à personne.</textarea></div></div></section>`)}
function newForm(kind){let title=kind==='new-prospect'?'Ajouter un prospect':kind==='new-quote'?'Créer un devis':'Créer un site';return layout(header('NOUVEAU',title,'Les informations seront analysées par votre agent IA.')+`<section class="panel" style="max-width:760px"><div class="form-grid"><div class="field"><label>Nom de l’entreprise</label><input id="new-name" placeholder="Ex. Maison Dupont" /></div><div class="field"><label>Secteur</label><select><option>Restaurant</option><option>Santé</option><option>Artisanat</option><option>Services professionnels</option></select></div><div class="field full"><label>Site actuel (optionnel)</label><input placeholder="https://..." /></div><div class="field full"><label>Brief ou notes</label><textarea placeholder="Décrivez le besoin du client..."></textarea></div></div><div style="display:flex;gap:10px;margin-top:22px"><button class="primary-btn" data-action="submit-form">✦ Analyser avec l’IA</button><button class="secondary-btn" data-page="overview">Annuler</button></div></section>`)}
function render(){let content=state.page==='overview'?overview():state.page==='prospects'?prospectsPage():state.page==='quotes'?quotesPage():state.page==='sites'?sitesPage():state.page==='library'?libraryPage():state.page==='settings'?settingsPage():newForm(state.page);app.innerHTML=content;bind()}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2800)}
function bind(){document.querySelectorAll('[data-page]').forEach(el=>el.onclick=()=>{state.page=el.dataset.page;document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===state.page));render()});document.querySelectorAll('[data-action]').forEach(el=>el.onclick=()=>{const a=el.dataset.action;if(['new-prospect','new-quote','new-site','new-universe'].includes(a)){state.page=a;render()}else if(a==='scan'){toast('Scan lancé : 42 nouvelles entreprises analysées.');}else if(a==='submit-form'){toast('Analyse terminée : opportunité notée 87/100.');setTimeout(()=>{state.page='prospects';render()},900)}else if(a==='save'){toast('Réglages enregistrés.')}});document.querySelectorAll('[data-prospect]').forEach(el=>el.onclick=()=>{const p=prospects[Number(el.dataset.prospect)];toast(`${p.name} — score d’opportunité ${p.score}/100`)});}
render();
