/* Main dashboard controller. Keeps navigation and feature entry points deterministic. */
(function () {
  const app = document.getElementById('app');
  const state = { page: 'overview' };
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const prospects = () => window.CPMProspects?.read?.() || [];
  const toast = (message) => { const node = document.getElementById('toast'); if (!node) return; node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2800); };
  const header = (eyebrow, title, subtitle, action = '') => `<div class="headline"><div><div class="eyebrow">${eyebrow}</div><h1 class="page-title">${title}</h1><p class="page-subtitle">${subtitle}</p></div>${action}</div>`;
  const button = (label, action, primary = true) => `<button class="button ${primary ? 'primary' : 'secondary'}" type="button" data-action="${action}">${label}</button>`;
  const overview = () => { const list = prospects(); return `<div class="page">${header('STUDIO LOCAL · AUJOURD’HUI','Pilotez votre agence avec clarté.','Créez, testez et livrez des sites professionnels depuis un espace unique.',button('+ Créer un site web','new-site'))}<div class="summary-grid"><article class="summary-card card"><h3>Prospects actifs</h3><strong>${list.length}</strong><span>opportunités suivies</span></article><article class="summary-card card"><h3>Score moyen</h3><strong>${list.length ? Math.round(list.reduce((sum, item) => sum + Number(item.score || 0), 0) / list.length) : 0}%</strong><span>qualité des opportunités</span></article><article class="summary-card card"><h3>Sites en production</h3><strong>3</strong><span>projets à livrer</span></article></div><div class="dashboard-grid"><section class="panel card"><h2>Opportunités prioritaires</h2><div class="mini-table">${list.slice(0,5).map((item) => `<div class="mini-row"><div><span>${escapeHtml(item.name)}</span><small>${escapeHtml(item.type || item.sector || 'Prospect')}</small></div><strong>${Number(item.score || 0)}%</strong></div>`).join('') || '<p class="page-subtitle">Ajoutez votre premier prospect pour commencer.</p>'}</div></section><section class="panel card"><h2>Actions rapides</h2><div class="quick-actions"><button class="quick-action" data-action="new-site"><span class="quick-icon">✦</span><span><b>Créer un site web</b><small>Générer une maquette professionnelle</small></span></button><button class="quick-action" data-page="tests"><span class="quick-icon">✓</span><span><b>Tester le système</b><small>Vérifier tous les modules</small></span></button><button class="quick-action" data-page="prospects"><span class="quick-icon">＋</span><span><b>Voir les prospects</b><small>Organiser votre pipeline</small></span></button></div></section></div></div>`; };
  const prospectsPage = () => `<div class="page">${header('PROSPECTION','Vos prospects','Classez les entreprises par potentiel et préparez vos prochaines actions.',button('+ Ajouter un prospect','new-prospect'))}<section class="panel card"><div class="table-wrap"><table><thead><tr><th>ENTREPRISE</th><th>SECTEUR</th><th>SCORE</th><th>STATUT</th><th>PROBLÈME DÉTECTÉ</th></tr></thead><tbody>${prospects().map((item) => `<tr><td><div class="entity"><span class="dot">${escapeHtml(item.icon || '•')}</span><div><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.city || '')}</small></div></div></td><td>${escapeHtml(item.type || item.sector || '—')}</td><td><span class="score-pill">${Number(item.score || 0)}%</span></td><td><span class="status">${escapeHtml(item.status || 'À qualifier')}</span></td><td>${escapeHtml(item.issue || 'À analyser')}</td></tr>`).join('') || '<tr><td colspan="5">Aucun prospect enregistré.</td></tr>'}</tbody></table></div></section></div>`;
  const simplePage = (eyebrow, title, subtitle, cards, action) => `<div class="page">${header(eyebrow,title,subtitle,button(action.label,action.action))}<div class="site-grid">${cards.map((card) => `<article class="card site-card"><h3>${card[0]}</h3><p>${card[1]}</p><span class="status">${card[2]}</span></article>`).join('')}</div></div>`;
  const render = () => { if (!app) return; if (state.page === 'tests') { window.CPMTestCenter?.render?.(); return; } if (state.page === 'prospects') app.innerHTML = prospectsPage(); else if (state.page === 'quotes') app.innerHTML = simplePage('VENTES','Devis & offres','Préparez des offres claires à partir de vos projets.',[['Site vitrine premium','Création et livraison sur mesure','À préparer'],['Pack maintenance','Suivi mensuel et évolutions','Disponible'],['Audit express','Diagnostic et recommandations','Modèle']],{label:'+ Créer un devis',action:'new-quote'}); else if (state.page === 'sites') app.innerHTML = simplePage('PRODUCTION','Sites en cours','Suivez les projets en préparation et les livraisons.',[['Projet client A','Maquette en validation','En cours'],['Projet client B','Contenu à compléter','À traiter'],['Projet client C','Prêt à exporter','Prêt']],{label:'+ Créer un site',action:'new-site'}); else if (state.page === 'library') app.innerHTML = simplePage('BIBLIOTHÈQUE','Univers visuels','Des directions artistiques prêtes à adapter.',[['Éditorial','Typographie et rythme premium','Disponible'],['Local business','Clair, direct et rassurant','Disponible'],['Signature','Contraste et caractère','Disponible']],{label:'+ Créer un univers',action:'new-universe'}); else if (state.page === 'settings') app.innerHTML = `<div class="page">${header('ESPACE','Réglages','Configurez votre environnement de production.',button('Enregistrer','save'))}<section class="panel card form-grid"><label>Nom de l’agence<input value="CavaPasMarcher" /></label><label>Devise<select><option>EUR — Euro</option><option>USD — Dollar</option></select></label></section></div>`; else app.innerHTML = overview(); bindContent(); };
  const bindContent = () => { app.querySelectorAll('[data-action]').forEach((node) => node.addEventListener('click', () => { const action = node.dataset.action; if (action === 'new-site') window.dispatchEvent(new CustomEvent('cpm:open-generator')); else if (action === 'new-prospect') toast('Le formulaire prospect sera disponible dans la prochaine étape.'); else toast('Action enregistrée.'); })); app.querySelectorAll('[data-page]').forEach((node) => node.addEventListener('click', () => { state.page = node.dataset.page; syncNav(); render(); })); };
  const syncNav = () => document.querySelectorAll('[data-page]').forEach((node) => node.classList.toggle('active', node.dataset.page === state.page));
  document.addEventListener('click', (event) => { const nav = event.target.closest('[data-page]'); if (!nav || !document.querySelector('.sidebar')?.contains(nav)) return; event.preventDefault(); state.page = nav.dataset.page; syncNav(); render(); }, true); document.addEventListener('click', (event) => { const action = event.target.closest('[data-action]')?.dataset.action; if (action === 'new-site') { window.setTimeout(() => document.querySelector('[data-action="new-site"]')?.dispatchEvent(new Event('cpm-generator-request')), 0); } }, true);
  window.CPMApp = { render, toast, state }; render();
})();
