/* CavaPasMarcher — country, language and pricing catalog.
   Country selection is ISO-based so the UI covers every country without a hand-written
   exception in the generator. Currency display uses Intl and the price engine uses
   configurable regional coefficients until a live FX/pricing service is connected. */
(function (global) {
  const codes = 'AF AL DZ AD AO AG AR AM AU AT AZ BS BH BD BB BY BE BZ BJ BT BO BA BW BR BN BG BF BI CV KH CM CA CF TD CL CN CO KM CG CD CR CI HR CU CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FJ FI FR GA GM GE DE GH GR GD GT GN GW GY HT HN HU IS IN ID IR IQ IE IL IT JM JP JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MG MW MY MV ML MT MH MR MU MX FM MD MC MN ME MA MZ MM NA NR NP NL NZ NI NE NG MK NO OM PK PW PA PG PY PE PH PL PT QA RO RU RW KN LC VC WS SM ST SA SN RS SC SL SG SK SI SB SO ZA SS ES LK SD SR SE CH SY TW TJ TZ TH TL TG TO TT TN TR TM TV UG UA AE GB US UY UZ VU VA VE VN YE ZM ZW'.split(' ');
  const names = {FR:'France',MA:'Maroc',BE:'Belgique',CH:'Suisse',CA:'Canada',US:'États-Unis',GB:'Royaume-Uni',ES:'Espagne',DE:'Allemagne',IT:'Italie',PT:'Portugal',NL:'Pays-Bas',DZ:'Algérie',TN:'Tunisie',SN:'Sénégal',CI:"Côte d’Ivoire",CM:'Cameroun',BJ:'Bénin',BR:'Brésil',MX:'Mexique',AR:'Argentine',CL:'Chili',CO:'Colombie',AU:'Australie',JP:'Japon',CN:'Chine',IN:'Inde',KR:'Corée du Sud',AE:'Émirats arabes unis',SA:'Arabie saoudite',TR:'Turquie',ZA:'Afrique du Sud',NG:'Nigeria',KE:'Kenya',GH:'Ghana',EG:'Égypte',RU:'Russie',UA:'Ukraine',PL:'Pologne',SE:'Suède',NO:'Norvège',DK:'Danemark',FI:'Finlande',AT:'Autriche',IE:'Irlande',GR:'Grèce',RO:'Roumanie',CZ:'Tchéquie',HU:'Hongrie',IL:'Israël',NZ:'Nouvelle-Zélande'};
  const currency = {FR:'EUR',MA:'MAD',BE:'EUR',CH:'CHF',CA:'CAD',US:'USD',GB:'GBP',ES:'EUR',DE:'EUR',IT:'EUR',PT:'EUR',NL:'EUR',DZ:'DZD',TN:'TND',SN:'XOF',CI:'XOF',CM:'XAF',BJ:'XOF',BR:'BRL',MX:'MXN',AR:'ARS',CL:'CLP',CO:'COP',AU:'AUD',JP:'JPY',CN:'CNY',IN:'INR',KR:'KRW',AE:'AED',SA:'SAR',TR:'TRY',ZA:'ZAR',NG:'NGN',KE:'KES',GH:'GHS',EG:'EGP',RU:'RUB',UA:'UAH',PL:'PLN',SE:'SEK',NO:'NOK',DK:'DKK',FI:'EUR',AT:'EUR',IE:'EUR',GR:'EUR',RO:'RON',CZ:'CZK',HU:'HUF',IL:'ILS',NZ:'NZD'};
  const language = {FR:['fr'],MA:['fr','ar','zgh'],BE:['fr','nl','de'],CH:['fr','de','it'],CA:['fr','en'],US:['en','es'],GB:['en'],ES:['es','ca','eu','gl'],DE:['de'],IT:['it'],PT:['pt'],NL:['nl'],DZ:['ar','fr','kab'],TN:['ar','fr'],SN:['fr','wo'],CI:['fr'],CM:['fr','en'],BR:['pt'],MX:['es'],AR:['es'],CL:['es'],CO:['es'],AU:['en'],JP:['ja'],CN:['zh'],IN:['hi','en'],KR:['ko'],AE:['ar','en'],SA:['ar'],TR:['tr'],ZA:['en','af','zu','xh'],NG:['en'],KE:['en','sw'],GH:['en'],EG:['ar','en'],RU:['ru'],UA:['uk'],PL:['pl'],SE:['sv'],NO:['no'],DK:['da'],FI:['fi','sv'],AT:['de'],IE:['en','ga'],GR:['el'],RO:['ro'],CZ:['cs'],HU:['hu'],IL:['he','ar'],NZ:['en','mi']};
  // Regional purchasing-power coefficients. Values are editable business policy, not a live FX feed.
  const factor = {EUR:1,CHF:1.12,GBP:1.02,CAD:.76,USD:.94,MAD:.34,DZD:.13,TND:.28,XOF:.22,XAF:.22,BRL:.29,MXN:.25,ARS:.16,CLP:.22,COP:.18,AUD:.82,JPY:.88,CNY:.34,INR:.21,KRW:.8,AED:.87,SAR:.78,TRY:.22,ZAR:.28,NGN:.12,KES:.2,GHS:.2,EGP:.17,RUB:.3,UAH:.18,PLN:.46,SEK:.72,NOK:.82,DKK:.73,RON:.36,CZK:.43,HUF:.29,ILS:.86,NZD:.75};
  const labels = {fr:{basic:'Basic',pro:'Pro',ultimate:'Ultime'},en:{basic:'Basic',pro:'Pro',ultimate:'Ultimate'},ar:{basic:'أساسي',pro:'احترافي',ultimate:'نهائي'},es:{basic:'Básico',pro:'Pro',ultimate:'Ultimate'},de:{basic:'Basic',pro:'Pro',ultimate:'Ultimate'},pt:{basic:'Básico',pro:'Pro',ultimate:'Ultimate'}};
  function list(){return codes.map(code=>({code,name:names[code]||code,currency:currency[code]||'USD',languages:language[code]||['en']}))}
  function pricing(code,sector,plan){const c=list().find(x=>x.code===code)||list()[0], f=factor[c.currency]||.5, nicheFactor=/sant|méd|med|jurid|avocat|finance|imm|hôtel|hotel/i.test(sector)?1.18:/restaurant|artisan|coiff|sport|local/i.test(sector)?.88:1;const base={basic:2900,pro:6900,ultimate:18900}[plan]||6900;const monthly={basic:149,pro:290,ultimate:690}[plan]||290;return {currency:c.currency,languages:c.languages,oneTime:base*f*nicheFactor,monthly:monthly*f*nicheFactor}}
  global.CPMCountries={list,pricing,labels};
})(window);
