/* Free local backup/restore for briefs, generated sites and settings. */
(function () {
  const keys = ['cpm-last-project', 'cpm-site-versions', 'cpm-session-user'];
  const toast = (message) => { const el = document.getElementById('toast'); if (!el) return; el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); };
  const download = (filename, value) => { const blob = new Blob([JSON.stringify(value, null, 2)], { type:'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 500); };
  function collect() { return { format:'cpm-local-backup', version:1, exportedAt:new Date().toISOString(), data:Object.fromEntries(keys.map((key) => [key, localStorage.getItem(key)])) }; }
  function restore(file) { const reader = new FileReader(); reader.onload = () => { try { const backup = JSON.parse(reader.result); if (backup.format !== 'cpm-local-backup' || !backup.data) throw new Error('format'); Object.entries(backup.data).forEach(([key, value]) => { if (keys.includes(key) && typeof value === 'string') localStorage.setItem(key, value); }); toast('Sauvegarde locale restaurée. Rechargez la page.'); } catch { toast('Fichier de sauvegarde invalide.'); } }; reader.readAsText(file); }
  document.addEventListener('click', (event) => { if (event.target.closest('[data-cpm-backup]')) { download(`cavapasmarcher-backup-${new Date().toISOString().slice(0,10)}.json`, collect()); toast('Sauvegarde locale téléchargée.'); } if (event.target.closest('[data-cpm-restore]')) document.getElementById('cpm-backup-file')?.click(); });
  document.addEventListener('change', (event) => { if (event.target.id === 'cpm-backup-file' && event.target.files[0]) restore(event.target.files[0]); });
  function addControls() { if (document.getElementById('cpm-backup-controls')) return; const settings = document.querySelector('[data-page="settings"]')?.closest('nav')?.parentElement; const target = document.querySelector('.page') || settings; if (!target) return; const controls = document.createElement('div'); controls.id='cpm-backup-controls'; controls.className='cpm-backup-controls'; controls.innerHTML='<strong>Sauvegarde gratuite</strong><span>Exportez vos données locales avant de changer de navigateur.</span><div><button type="button" class="secondary-btn" data-cpm-backup>Exporter</button><button type="button" class="secondary-btn" data-cpm-restore>Importer</button><input id="cpm-backup-file" type="file" accept="application/json" hidden></div>'; target.appendChild(controls); }
  new MutationObserver(addControls).observe(document.body, { childList:true, subtree:true }); addControls();
})();
