/* Saved projects workspace. It augments the static dashboard without breaking offline mode. */
(function () {
  const API = window.CPM_API_URL || 'http://localhost:8787/api';
  const app = () => document.getElementById('app');
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const money = (value, currency) => { try { return new Intl.NumberFormat('fr-FR', { style:'currency', currency, maximumFractionDigits:0 }).format(value); } catch { return `${Math.round(value || 0)} ${currency || ''}`; } };
  const localProjects = () => { try { const item = JSON.parse(localStorage.getItem('cpm-last-project') || 'null'); return item ? [item] : []; } catch { return []; } };
  async function fetchProjects() { try { const response = await fetch(`${API}/projects`); if (!response.ok) throw new Error('API'); return (await response.json()).projects || []; } catch { return localProjects(); } }
  function card(project) { const pricing = project.pricing || {}; return `<article class="saved-project card"><div class="saved-project-cover"><span>${esc(project.sector || 'Projet web')}</span><strong>${esc(project.name || 'Projet sans nom')}</strong><small>${esc(project.city || project.country || 'International')} · ${esc(project.plan || 'pro').toUpperCase()}</small></div><div class="saved-project-body"><div><strong>${esc(project.name || 'Projet sans nom')}</strong><small>${esc(project.sector || 'Secteur non renseigné')}</small></div><span class="project-status">${project.localOnly ? 'Local' : 'Enregistré'}</span><div class="saved-project-meta"><span>${pricing.oneTime ? money(pricing.oneTime, pricing.currency) : 'Prix à définir'}</span><span>${esc(project.language || 'fr').toUpperCase()}</span></div><div class="saved-project-actions"><button class="secondary-btn" data-project-open="${esc(project.id || '')}">Ouvrir le brief</button>${project.id && !project.localOnly ? `<button class="danger-btn" data-project-delete="${esc(project.id)}">Supprimer</button>` : ''}</div></div></article>`; }
  async function renderSavedProjects() { const root = app(); if (!root) return; root.innerHTML = `<div class="page saved-projects-page"><div class="headline"><div><div class="eyebrow">PRODUCTION</div><h1 class="page-title">Sites enregistrés</h1><p class="page-subtitle">Retrouvez les briefs, tarifs et variantes de chaque entreprise.</p></div><button class="primary-btn" data-action="new-site">+ Nouveau site</button></div><div class="saved-project-toolbar"><span id="saved-project-count">Chargement…</span><button class="secondary-btn" id="refresh-projects">↻ Actualiser</button></div><div class="saved-project-grid" id="saved-project-grid"><div class="panel empty">Chargement des projets…</div></div></div>`; const projects = await fetchProjects(); const grid = document.getElementById('saved-project-grid'); const count = document.getElementById('saved-project-count'); if (!grid || !count) return; count.textContent = `${projects.length} projet${projects.length > 1 ? 's' : ''} enregistré${projects.length > 1 ? 's' : ''}`; grid.innerHTML = projects.length ? projects.map(card).join('') : `<div class="panel empty"><div style="font-size:42px">✦</div><strong>Aucun site enregistré</strong><br>Générez votre premier site depuis le bouton Nouveau site.</div>`; bindProjects(); }
  function bindProjects() { document.getElementById('refresh-projects')?.addEventListener('click', renderSavedProjects); document.querySelectorAll('[data-project-delete]').forEach((button) => button.addEventListener('click', async () => { if (!confirm('Supprimer définitivement ce projet ?')) return; try { const response = await fetch(`${API}/projects/${encodeURIComponent(button.dataset.projectDelete)}`, { method:'DELETE' }); if (!response.ok) throw new Error('delete'); renderSavedProjects(); } catch { alert('Le serveur API doit être lancé pour supprimer ce projet.'); } })); document.querySelectorAll('[data-project-open]').forEach((button) => button.addEventListener('click', () => { const project = localProjects().find((item) => item.id === button.dataset.projectOpen); if (project) { localStorage.setItem('cpm-open-project', JSON.stringify(project)); } window.dispatchEvent(new CustomEvent('cpm:open-project', { detail: button.dataset.projectOpen })); document.querySelector('[data-action="new-site"]')?.click(); })); }
  document.addEventListener('click', (event) => { const nav = event.target.closest('[data-page="sites"]'); if (nav) { event.preventDefault(); event.stopImmediatePropagation(); renderSavedProjects(); } }, true);
  window.CPMSavedProjects = { render: renderSavedProjects };
})();
