/* Saved projects workspace with authenticated API requests and offline fallback. */
(function () {
  const API = window.CPM_API_URL || 'http://localhost:8787/api';
  const app = () => document.getElementById('app');
  const token = () => window.CPMAuth?.token?.() || window.CPM_API_TOKEN || localStorage.getItem('cpm-session-token') || '';
  const headers = () => ({ ...(token() ? { authorization:`Bearer ${token()}` } : {}) });
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
  const money = (value, currency) => { try { return new Intl.NumberFormat('fr-FR', { style:'currency', currency, maximumFractionDigits:0 }).format(value); } catch { return `${Math.round(value || 0)} ${currency || ''}`; } };
  const localProjects = () => { try { const item = JSON.parse(localStorage.getItem('cpm-last-project') || 'null'); return item ? [item] : []; } catch { return []; } };
  async function fetchProjects() { try { const response = await fetch(`${API}/projects`, { headers:headers() }); if (!response.ok) throw new Error('API'); return (await response.json()).projects || []; } catch { return localProjects(); } }
  function card(project) { const pricing = project.pricing || {}; const id = esc(project.id || 'local'); return `<article class="saved-project card"><div class="saved-project-cover"><span>${esc(project.sector || 'Projet web')}</span><strong>${esc(project.country || 'FR')}</strong></div><div class="saved-project-body"><div class="saved-project-title"><h3>${esc(project.name || 'Projet sans nom')}</h3><span>${esc(String(project.plan || 'pro').toUpperCase())}</span></div><p>${esc(project.city || 'Localisation non renseignée')}</p><div class="saved-project-price">${pricing.monthly ? `${money(pricing.monthly, pricing.currency)} / mois` : 'Pricing à calculer'}</div><div class="saved-project-actions"><button class="primary-btn" data-project-open="${id}">Ouvrir</button><button class="secondary-btn" data-project-delete="${id}">Supprimer</button></div></div></article>`; }
  async function renderSavedProjects() { const root = app(); if (!root) return; const projects = await fetchProjects(); root.innerHTML = `<div class="page saved-projects-page"><div class="headline"><div><div class="eyebrow">PRODUCTION</div><h1 class="page-title">Sites en cours</h1><p class="page-subtitle">Retrouvez vos projets sauvegardés, même en mode local.</p></div><button class="primary-btn" data-action="new-site">+ Nouveau site</button></div><div class="saved-project-grid">${projects.length ? projects.map(card).join('') : '<div class="empty-state">Aucun site sauvegardé.</div>'}</div></div>`; bindProjects(); }
  function bindProjects() { document.querySelector('[data-action="new-site"]')?.addEventListener('click', () => document.querySelector('[data-page="overview"]')?.click()); document.querySelectorAll('[data-project-delete]').forEach((button) => button.addEventListener('click', async () => { const id = button.dataset.projectDelete; if (!id || id === 'local') return; if (!window.confirm('Supprimer définitivement ce projet ?')) return; try { const response = await fetch(`${API}/projects/${encodeURIComponent(id)}`, { method:'DELETE', headers:headers() }); if (!response.ok) throw new Error(); window.dispatchEvent(new CustomEvent('cpm:projects-changed')); renderSavedProjects(); } catch { const message = document.getElementById('toast'); if (message) { message.textContent = 'Suppression impossible sans connexion API.'; message.classList.add('show'); } } })); }
  document.addEventListener('click', (event) => { const nav = event.target.closest('[data-page="sites"]'); if (nav) { event.preventDefault(); event.stopImmediatePropagation(); renderSavedProjects(); } }, true);
  window.addEventListener('cpm:auth-changed', renderSavedProjects); window.addEventListener('cpm:projects-changed', renderSavedProjects); window.CPMSavedProjects = { render:renderSavedProjects };
})();
