import http from 'node:http';
import { randomUUID } from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const dataFile = join(root, 'data', 'projects.json');
const port = Number(process.env.PORT || 8787);
const allowedPlans = new Set(['basic', 'pro', 'ultimate']);
const allowedCountries = new Set(['AF','AL','DZ','AD','AO','AG','AR','AM','AU','AT','AZ','BS','BH','BD','BB','BY','BE','BZ','BJ','BT','BO','BA','BW','BR','BN','BG','BF','BI','CV','KH','CM','CA','CF','TD','CL','CN','CO','KM','CG','CD','CR','CI','HR','CU','CY','CZ','DK','DJ','DM','DO','EC','EG','SV','GQ','ER','EE','SZ','ET','FJ','FI','FR','GA','GM','GE','DE','GH','GR','GD','GT','GN','GW','GY','HT','HN','HU','IS','IN','ID','IR','IQ','IE','IL','IT','JM','JP','JO','KZ','KE','KI','KP','KR','KW','KG','LA','LV','LB','LS','LR','LY','LI','LT','LU','MG','MW','MY','MV','ML','MT','MH','MR','MU','MX','FM','MD','MC','MN','ME','MA','MZ','MM','NA','NR','NP','NL','NZ','NI','NE','NG','MK','NO','OM','PK','PW','PA','PG','PY','PE','PH','PL','PT','QA','RO','RU','RW','KN','LC','VC','WS','SM','ST','SA','SN','RS','SC','SL','SG','SK','SI','SB','SO','ZA','SS','ES','LK','SD','SR','SE','CH','SY','TW','TJ','TZ','TH','TL','TG','TO','TT','TN','TR','TM','TV','UG','UA','AE','GB','US','UY','UZ','VU','VA','VE','VN','YE','ZM','ZW']);
const currency = { FR:'EUR',MA:'MAD',BE:'EUR',CH:'CHF',CA:'CAD',US:'USD',GB:'GBP',DZ:'DZD',TN:'TND',SN:'XOF',CI:'XOF',CM:'XAF',BR:'BRL',MX:'MXN',AR:'ARS',CL:'CLP',CO:'COP',AU:'AUD',JP:'JPY',CN:'CNY',IN:'INR',KR:'KRW',AE:'AED',SA:'SAR',TR:'TRY',ZA:'ZAR',NG:'NGN',KE:'KES',GH:'GHS',EG:'EGP',RU:'RUB',UA:'UAH',PL:'PLN',SE:'SEK',NO:'NOK',DK:'DKK',RO:'RON',CZ:'CZK',HU:'HUF',IL:'ILS',NZ:'NZD' };
const factor = { EUR:1, CHF:1.12, GBP:1.02, CAD:.76, USD:.94, MAD:.34, DZD:.13, TND:.28, XOF:.22, XAF:.22, BRL:.29, MXN:.25, ARS:.16, CLP:.22, COP:.18, AUD:.82, JPY:.88, CNY:.34, INR:.21, KRW:.8, AED:.87, SAR:.78, TRY:.22, ZAR:.28, NGN:.12, KES:.2, GHS:.2, EGP:.17, RUB:.3, UAH:.18, PLN:.46, SEK:.72, NOK:.82, DKK:.73, RON:.36, CZK:.43, HUF:.29, ILS:.86, NZD:.75 };
const base = { basic: [2900,149], pro: [6900,290], ultimate: [18900,690] };

async function loadProjects() { try { return JSON.parse(await readFile(dataFile, 'utf8')); } catch { return []; } }
async function saveProjects(projects) { await mkdir(dirname(dataFile), { recursive: true }); await writeFile(dataFile, JSON.stringify(projects, null, 2)); }
function json(res, status, body) { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store', 'access-control-allow-origin': '*' }); res.end(JSON.stringify(body)); }
function pricing(country, sector, plan) { const code = String(country || 'FR').toUpperCase(); const selected = allowedCountries.has(code) ? code : 'FR'; const curr = currency[selected] || 'USD'; const niche = /sant|méd|med|jurid|avocat|finance|imm|hôtel|hotel/i.test(String(sector || '')) ? 1.18 : /restaurant|artisan|coiff|sport|local/i.test(String(sector || '')) ? .88 : 1; const [oneTime, monthly] = base[plan] || base.pro; return { country: selected, currency: curr, plan: allowedPlans.has(plan) ? plan : 'pro', oneTime: Math.round(oneTime * (factor[curr] || .5) * niche), monthly: Math.round(monthly * (factor[curr] || .5) * niche), pricingVersion: '2026-01' }; }
function validProject(body) { if (!body || typeof body !== 'object') return 'Invalid JSON object'; if (!String(body.name || '').trim() || !String(body.sector || '').trim()) return 'name and sector are required'; if (String(body.name).length > 140 || String(body.description || '').length > 4000) return 'field length exceeded'; if (body.plan && !allowedPlans.has(body.plan)) return 'invalid plan'; if (body.country && !allowedCountries.has(String(body.country).toUpperCase())) return 'invalid country'; return null; }
async function handler(req, res) { const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); if (req.method === 'OPTIONS') { res.writeHead(204, { 'access-control-allow-origin':'*', 'access-control-allow-methods':'GET,POST,DELETE,OPTIONS', 'access-control-allow-headers':'content-type' }); return res.end(); } if (url.pathname === '/api/health') return json(res, 200, { ok:true, service:'cpm-studio-api' }); if (url.pathname === '/api/countries' && req.method === 'GET') return json(res, 200, { countries:[...allowedCountries].map(code => ({ code, currency:currency[code] || 'USD' })) }); if (url.pathname === '/api/pricing' && req.method === 'GET') return json(res, 200, pricing(url.searchParams.get('country'), url.searchParams.get('sector'), url.searchParams.get('plan')));
  if (url.pathname === '/api/projects' && req.method === 'GET') return json(res, 200, { projects: await loadProjects() });
  if (url.pathname === '/api/projects' && req.method === 'POST') { let body=''; for await (const chunk of req) { body += chunk; if (body.length > 100000) return json(res, 413, { error:'payload too large' }); } let data; try { data=JSON.parse(body); } catch { return json(res, 400, { error:'invalid JSON' }); } const error=validProject(data); if (error) return json(res, 422, { error }); const projects=await loadProjects(); const project={ id:randomUUID(), createdAt:new Date().toISOString(), updatedAt:new Date().toISOString(), name:String(data.name).trim(), sector:String(data.sector).trim(), country:String(data.country || 'FR').toUpperCase(), city:String(data.city || '').trim(), plan:data.plan || 'pro', language:data.language || 'fr', languages:Array.isArray(data.languages) ? data.languages.slice(0,12) : [], description:String(data.description || '').trim(), pricing:pricing(data.country, data.sector, data.plan || 'pro') }; projects.unshift(project); await saveProjects(projects); return json(res, 201, project); }
  const match=url.pathname.match(/^\/api\/projects\/([^/]+)$/); if (match && req.method === 'GET') { const project=(await loadProjects()).find(x=>x.id===match[1]); return project ? json(res,200,project) : json(res,404,{error:'project not found'}); } if (match && req.method === 'DELETE') { const projects=await loadProjects(); const next=projects.filter(x=>x.id!==match[1]); if (next.length===projects.length) return json(res,404,{error:'project not found'}); await saveProjects(next); return json(res,204,null); } return json(res,404,{error:'route not found'}); }
http.createServer((req,res)=>handler(req,res).catch(error=>json(res,500,{error:'internal server error',detail:process.env.NODE_ENV==='development'?error.message:undefined}))).listen(port,()=>console.log(`CPM API listening on http://localhost:${port}`));
